{% set name = "cappa" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cappa-{{ version }}.tar.gz
  sha256: 9a3c45255e2da19c397343dff0164dd0bbdaec9a1ca4721b692421b0c7b6cdd4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8,<4.0
    - typing-extensions >=4.7.1
    - typing_inspect >=0.9.0
    - rich
  run_constrained:
    - docstring-parser >=0.15

test:
  imports:
    - cappa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dancardin/cappa
  summary: Declarative CLI argument parser.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
