{% set name = "cappa" %}
{% set version = "0.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cappa-{{ version }}.tar.gz
  sha256: 32265d60201dc166b45dc110fda93e21e7fea21aad15fd4c82a8741990d6be23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.8.0
    - type-lens >=0.2.3
    - rich
  run_constrained:
    - docstring-parser >=0.15

test:
  imports:
    - cappa
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dancardin/cappa
  summary: Declarative CLI argument parser.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
