{% set name = "cappa" %}
{% set version = "0.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cappa-{{ version }}.tar.gz
  sha256: 0695c06c26686e3b7fff4fef202525978472d75a5c84de20b084818d38c46abc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8,<4.0
    - typing-extensions >=4.8.0
    - typing_inspect >=0.9.0
    - rich
  run_constrained:
    - docstring-parser >=0.15

test:
  imports:
    - cappa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dancardin/cappa
  summary: Declarative CLI argument parser.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
