{% set name = "cappa" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cappa-{{ version }}.tar.gz
  sha256: 7ab3dc7a13c09e48e76153370a6845095bbe5cbe1bc979ec7877b193020e68ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - hatchling
    - pip
  run:
    - python >=3.8,<4.0
    - typing-extensions >=4.8.0
    - typing_inspect >=0.9.0
    - rich
  run_constrained:
    - docstring-parser >=0.15

test:
  imports:
    - cappa
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dancardin/cappa
  summary: Declarative CLI argument parser.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
